apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: app
      context: .
  local: {}

deploy:
  helm:
    releases:
      - name: app
        chartPath: helm/app
        wait: true
        values:
          image: app

portForward:
  - resourceType: service
    resourceName: app
    port: 5555
